"""
╔════════════════════════════════════════════════════════════════════════════╗
║                           AI-GENERATED TEST FILE                           ║
║                                                                            ║
║  Generated by: GitHub Copilot (Claude 3.5)                                 ║
║  Model: claude-3-5-sonnet-20241022                                         ║
║  Confidence in core logic: ~85-90%                                         ║
║                                                                            ║
║  ⚠️  DISCLAIMER:                                                           ║
║  This is a baseline template. YOU MUST REVIEW EVERY TEST carefully.        ║
║  Verify that:                                                              ║
║    1. Test logic matches your actual function behavior                     ║
║    2. Fixture data format is correct for your DataFrame structure          ║
║    3. Error messages match exactly what your function raises               ║
║    4. Edge cases are handled properly                                      ║
║    5. Comments are accurate and helpful                                    ║
║                                                                            ║
║  Expected accuracy: Core test structure is solid, but parameter values     ║
║  and specific assertions may need adjustment based on actual behavior.     ║
╚════════════════════════════════════════════════════════════════════════════╝
"""

import pytest

# Import the function we're testing
import multiplied as mp


# ============================================================================
# NO FIXTURE DEFINITIONS HERE - ALL COME FROM conftest.py
# Available fixtures:
#   - sample_heatmap_dataframe (from conftest.py)
#   - temp_svg_output (from conftest.py)
#   - real_truth_dataframe_small (from conftest.py)
#   - large_heatmap_dataframe (from conftest.py)
#   - cleanup_matplotlib (autouse - automatic)
# ============================================================================


# ============================================================================
# TIER 1: FILE OUTPUT TESTS
# Tests that files are created with basic validity
# ============================================================================


class TestTier1_FileOutputBasics:
    """
    TEST GROUP: Basic file creation and existence

    PURPOSE:
        These tests verify that:
        1. The function creates a file at the specified path
        2. The file is not empty
        3. The file can be found on disk

    WHAT'S TESTED:
        ✓ File exists after function call
        ✓ File has content (size > 0)
        ✗ Visual correctness (NOT tested here)
        ✗ Data accuracy (NOT tested here)

    AI CONFIDENCE: ~90%
        Basic file operations are straightforward. Main uncertainty:
        - Whether file path handling matches system (Windows vs Linux)
        - Whether function overwrites existing files
    """

    def test_heatmap_creates_svg_file(self, sample_heatmap_dataframe, temp_output_path):
        """
        TEST: File creation - SVG format

        WHAT IT DOES:
            1. Calls df_global_heatmap() with required parameters
            2. Checks if the file was created

        EXPECTED RESULT:
            File should exist after function call

        WHY IT MATTERS:
            If file isn't created, all subsequent functionality fails.
            This is the "smoke test" of the file system.

        AI CONFIDENCE: ~95%
        """
        # Call the heatmap function
        # Parameters: path, title, dataframe, dark (keyword-only)
        mp.df_global_heatmap(
            str(temp_output_path),  # Where to save the file
            "Test Heatmap Title",  # Title for the plot
            sample_heatmap_dataframe,  # Data to plot
        )

        # ASSERTION: Check that file exists
        # Path.exists() returns True if file is on disk, False otherwise
        assert temp_output_path.exists(), (
            f"Expected SVG file to be created at {temp_output_path}, but it doesn't exist"
        )

    def test_heatmap_file_has_content(self, sample_heatmap_dataframe, temp_output_path):
        """
        TEST: File content - Not empty/corrupted

        WHAT IT DOES:
            1. Creates heatmap file
            2. Checks file size

        EXPECTED RESULT:
            File size should be > 1000 bytes (SVG with actual content)

        WHY IT MATTERS:
            A 0-byte file indicates the function ran but didn't write anything.
            A tiny file (<100 bytes) suggests file corruption or incomplete write.

        AI CONFIDENCE: ~85%
            File size depends on:
            - DataFrame size
            - Figure resolution (16x9, 200 dpi in actual function)
            - SVG compression
            I'm ~85% confident 1000 bytes is the right threshold.
            You may need to adjust based on actual output.
        """
        # Create the heatmap
        mp.df_global_heatmap(
            str(temp_output_path), "Test Heatmap Title", sample_heatmap_dataframe
        )

        # Get file size in bytes
        file_size = temp_output_path.stat().st_size

        # ASSERTION: File should have reasonable size
        assert file_size > 1000, (
            f"SVG file size is {file_size} bytes. Expected > 1000. "
            f"File may be corrupted or empty."
        )

        # ASSERTION: File shouldn't be suspiciously huge
        assert file_size < 10_000_000, (
            f"SVG file size is {file_size} bytes. Expected < 10MB. "
            f"File may contain uncompressed data or be corrupted."
        )


# ============================================================================
# TIER 2: BASIC ERROR HANDLING
# Tests that function rejects invalid inputs with appropriate errors
# ============================================================================


class TestTier2_InputValidation:
    """
    TEST GROUP: Input validation - does function reject bad inputs?

    PURPOSE:
        The function has type checking at the start:
        - df must be pandas.DataFrame
        - title must be str
        - path must be str

        These tests verify those checks work.

    WHAT'S TESTED:
        ✓ TypeError raised for non-DataFrame input
        ✓ TypeError raised for non-string title
        ✓ TypeError raised for non-string path
        ✗ Correct error messages (partially tested)

    AI CONFIDENCE: ~90%
        The function has explicit type checking, so this is straightforward.
        Uncertainty is only in exact error message text.
    """

    def test_rejects_non_dataframe_input(self, temp_output_path):
        """
        TEST: Validates input is DataFrame

        WHAT IT DOES:
            1. Tries to call function with a list instead of DataFrame
            2. Expects TypeError to be raised

        EXPECTED RESULT:
            Should raise TypeError with message containing "df must be a pandas DataFrame"

        WHY IT MATTERS:
            Prevents users from accidentally passing wrong data type.
            Function will crash if df isn't a DataFrame, so catching early is good.

        AI CONFIDENCE: ~95%
            Function has explicit check:
            ```
            if not isinstance(df, pd.DataFrame):
                raise TypeError("df must be a pandas DataFrame")
            ```
            This is guaranteed to work.
        """
        # Try to call with a list instead of DataFrame
        bad_data = [1, 2, 3, 4, 5]

        # pytest.raises() catches exceptions for testing
        # It verifies:
        # 1. Exception type (TypeError)
        # 2. Exception message contains text (match parameter)
        with pytest.raises(TypeError, match="df must be a pandas DataFrame"):
            mp.df_global_heatmap(
                str(temp_output_path),
                "Test Title",
                bad_data,  # ⚠️ WRONG: Should be DataFrame
            )

    def test_rejects_non_string_title(self, sample_heatmap_dataframe, temp_output_path):
        """
        TEST: Validates title is string

        WHAT IT DOES:
            1. Tries to pass integer as title
            2. Expects TypeError

        EXPECTED RESULT:
            Should raise TypeError

        WHY IT MATTERS:
            Title is used in plot rendering. Non-string will cause crash.

        AI CONFIDENCE: ~95%
            Function has explicit check for title type.
        """
        with pytest.raises(TypeError, match="title must be a string"):
            mp.df_global_heatmap(
                str(temp_output_path),
                123,  # ⚠️ WRONG: Should be string
                sample_heatmap_dataframe,
            )

    def test_rejects_non_string_path(self, sample_heatmap_dataframe):
        """
        TEST: Validates path is string

        WHAT IT DOES:
            1. Tries to pass integer as path
            2. Expects TypeError

        EXPECTED RESULT:
            Should raise TypeError

        WHY IT MATTERS:
            Path is used for file I/O. Wrong type = crash.

        AI CONFIDENCE: ~95%
            Function has explicit check for path type.
        """
        with pytest.raises(TypeError, match="path must be a string"):
            mp.df_global_heatmap(
                12345,  # ⚠️ WRONG: Should be string
                "Test Title",
                sample_heatmap_dataframe,
            )


# ============================================================================
# TIER 3: DATA INTEGRITY
# Tests that function doesn't mutate input data
# ============================================================================


class TestTier3_DataIntegrity:
    """
    TEST GROUP: Input data isn't modified

    PURPOSE:
        Verify that calling df_global_heatmap() doesn't have side effects
        on the input DataFrame. Function should only READ data, not WRITE.

    WHAT'S TESTED:
        ✓ DataFrame shape unchanged
        ✓ DataFrame columns unchanged
        ✓ DataFrame values unchanged

    AI CONFIDENCE: ~90%
        Function uses .sum() and slicing which create copies, so original
        shouldn't be modified. But "should" ≠ "definitely" at 100%.
    """

    def test_dataframe_not_mutated(self, sample_heatmap_dataframe, temp_output_path):
        """
        TEST: Function doesn't modify input DataFrame

        WHAT IT DOES:
            1. Record DataFrame properties (shape, columns, values) BEFORE
            2. Call heatmap function
            3. Record DataFrame properties AFTER
            4. Compare - they should be identical

        EXPECTED RESULT:
            All properties unchanged

        WHY IT MATTERS:
            Users might reuse DataFrame for other operations.
            If function modifies it, causes hard-to-debug errors downstream.

        AI CONFIDENCE: ~90%
        """
        # Record original state
        original_shape = sample_heatmap_dataframe.shape
        original_columns = list(sample_heatmap_dataframe.columns)
        original_values = sample_heatmap_dataframe.values.copy()
        original_index = sample_heatmap_dataframe.index.tolist()

        # Call the function
        mp.df_global_heatmap(
            str(temp_output_path), "Test Title", sample_heatmap_dataframe
        )

        # ASSERTION: Shape should be unchanged
        assert sample_heatmap_dataframe.shape == original_shape, (
            f"DataFrame shape changed: {original_shape} → {sample_heatmap_dataframe.shape}"
        )

        # ASSERTION: Columns should be unchanged
        assert list(sample_heatmap_dataframe.columns) == original_columns, (
            "DataFrame columns changed"
        )

        # ASSERTION: Values should be unchanged
        assert (sample_heatmap_dataframe.values == original_values).all(), (
            "DataFrame values were modified"
        )

        # ASSERTION: Index should be unchanged
        assert sample_heatmap_dataframe.index.tolist() == original_index, (
            "DataFrame index changed"
        )


# ============================================================================
# TIER 4: FUNCTION BEHAVIOR WITH DIFFERENT PARAMETERS
# Tests that function works with various valid inputs
# ============================================================================


class TestTier4_ParameterVariations:
    """
    TEST GROUP: Function works with different valid inputs

    PURPOSE:
        Real-world usage will have varying:
        - DataFrame sizes
        - Title lengths
        - File paths
        - dark parameter values

        These tests verify function doesn't break with variations.

    WHAT'S TESTED:
        ✓ Different title lengths/content
        ✓ Different file formats (.svg, .png)
        ✓ dark=True vs dark=False

    AI CONFIDENCE: ~85%
        Function should handle these, but matplotlib rendering could have
        edge cases. Mostly confident, but not 100%.
    """

    def test_heatmap_with_various_titles(self, sample_heatmap_dataframe, tmp_path):
        """
        TEST: Function accepts different title formats

        WHAT IT DOES:
            1. Test with short title
            2. Test with long title
            3. Test with special characters
            4. Test with empty title

        EXPECTED RESULT:
            All should create valid files without error

        WHY IT MATTERS:
            Users will pass various titles. Function should be robust.

        AI CONFIDENCE: ~85%
            Matplotlib can render various strings, but there could be
            edge cases with special characters or very long strings.
        """
        test_titles = [
            "Simple",  # Short title
            "Wallace Tree 8-bit Heatmap",  # Typical title
            "Title with numbers 12345",  # Numbers included
            "Title-with_Special.Chars!",  # Special characters
            "",  # Empty title
        ]

        for i, title in enumerate(test_titles):
            output_path = tmp_path / f"test_{i}.svg"

            # Should not raise any exception
            try:
                mp.df_global_heatmap(str(output_path), title, sample_heatmap_dataframe)

                # ASSERTION: File should be created
                assert output_path.exists(), (
                    f"Failed to create file with title: '{title}'"
                )

            except Exception as e:
                pytest.fail(
                    f"Function raised {type(e).__name__} with title '{title}': {e}"
                )

    def test_heatmap_dark_theme_parameter(self, sample_heatmap_dataframe, tmp_path):
        """
        TEST: dark parameter works (True and False)

        WHAT IT DOES:
            1. Create heatmap with dark=False (default)
            2. Create heatmap with dark=True
            3. Verify both files are created

        EXPECTED RESULT:
            Both should succeed and create files

        WHY IT MATTERS:
            Dark theme is optional feature. Should work in both modes.

        AI CONFIDENCE: ~90%
            dark parameter is just a boolean affecting matplotlib style.
            Should work reliably.
        """
        light_path = tmp_path / "light.svg"
        dark_path = tmp_path / "dark.svg"

        # Create with light theme (default)
        mp.df_global_heatmap(
            str(light_path), "Test Title", sample_heatmap_dataframe, dark=False
        )

        # Create with dark theme
        mp.df_global_heatmap(
            str(dark_path), "Test Title", sample_heatmap_dataframe, dark=True
        )

        # ASSERTION: Both files should exist
        assert light_path.exists(), "Light theme file not created"
        assert dark_path.exists(), "Dark theme file not created"

        # Both should have content
        assert light_path.stat().st_size > 1000
        assert dark_path.stat().st_size > 1000


# ============================================================================
# SUMMARY OF TEST COVERAGE
# ============================================================================

"""
TESTS WRITTEN:
  ✓ TIER 1: File Creation (2 tests)
    - SVG file is created
    - SVG file has content

  ✓ TIER 2: Input Validation (3 tests)
    - Rejects non-DataFrame input
    - Rejects non-string title
    - Rejects non-string path

  ✓ TIER 3: Data Integrity (1 test)
    - Input DataFrame not mutated

  ✓ TIER 4: Parameter Variations (2 tests)
    - Various title formats work
    - dark parameter works (True/False)

TOTAL: 8 basic tests

WHAT'S NOT TESTED (intentionally):
  ✗ Visual correctness of plots
  ✗ Exact colors/fonts
  ✗ SVG internal structure details
  ✗ PNG/JPG export (separate file)
  ✗ Performance/speed

NEXT STEPS:
  1. Run these tests: pytest tests/test_heatmap_basic.py -v
  2. Review any failures and adjust fixture data or assertions
  3. Add tests/test_heatmap_visual.py for visual checks
"""
